---
title: "Mapping Sample Site Locations of Malaspina, TARA, GOS, and OSD"
output: html_notebook
---

```{r}
setwd("~/Desktop/msc/ms_mgg/src/contextual_data/")
library(tidyverse)
library(ggplot2)
library(rworldmap)
library(scales)
```

```{r}
contextual_data <- read_tsv("~/Desktop/msc/contextualdata/sample_data/compiled_metadata.txt", col_names = TRUE)

Samples_unsequenced <- bind_rows(read_tsv("~/Desktop/msc/contextualdata/sample_data/GOS_samples_unsequenced.txt", col_names = TRUE),
read_tsv("~/Desktop/msc/contextualdata/sample_data/TARA_samples_unsequenced.txt", col_names = TRUE))

contextual_data_edited <- mutate(contextual_data, Sequenced = ifelse(contextual_data$Sample %in% Samples_unsequenced$label, "no", "yes"))
```


Map of sample sites for TARA, Malaspina, OSD, GOS. If there is an "X" then a sample at the site may not of been sequenced
```{r}
map.world <- map_data(map="world")

ggplot()+
     geom_map(data=map.world, map=map.world, aes(map_id=region, x=long, y=lat))+
     geom_point(data = contextual_data_edited, aes(x=Longitude, y=Latitude, color = Project, shape = Sequenced, size = Sequenced)) +
     scale_size_manual(values = c(3,1)) +
     scale_shape_manual(values = c(4,19)) +
     coord_equal() +
     theme_bw() +
     theme(legend.position = "bottom",
           axis.title = element_blank(),
           axis.text = element_blank(),
           axis.ticks = element_blank()) 

# guide_legend(title.position = "bottom", nrow = 2) 

```

Mapping sample data along with temperature
```{r}
map.world <- map_data(map="world")

ggplot()+
     geom_map(data=map.world, map=map.world, aes(map_id=region, x=long, y=lat))+
     geom_point(data = contextual_data_edited, aes(x=Longitude, y=Latitude, color = Temperature_C, shape = Sequenced, size = Sequenced)) +
     scale_size_manual(values = c(4,4)) +
     scale_shape_manual(values = c(4,19)) +
     scale_color_gradient(low = "yellow", high = "red") +
     coord_equal() +
     theme_bw() +
     theme(legend.position = "bottom",
           axis.title = element_blank(),
           axis.text = element_blank(),
           axis.ticks = element_blank()) 
```

Mapping sample data along with salinity
```{r}
map.world <- map_data(map="world")

ggplot()+
     geom_map(data=map.world, map=map.world, aes(map_id=region, x=long, y=lat))+
     geom_point(data = contextual_data_edited, aes(x=Longitude, y=Latitude, color = Salinity_psu, shape = Sequenced, size = Sequenced)) +
     scale_size_manual(values = c(4,4)) +
     scale_shape_manual(values = c(4,19)) +
     scale_color_gradient(low = "yellow", high = "blue") +
     coord_equal() +
     theme_bw() +
     theme(legend.position = "bottom",
           axis.title = element_blank(),
           axis.text = element_blank(),
           axis.ticks = element_blank()) 
```

